### ISSUE TITLE
Create CI builds

### ISSUE THREAD

**Issue by akileos** [dereulenspiegel/HABSweetie#5]
For patch testing ;)

https://developer.cloudbees.com/bin/view/DEV/Continuous+Integration+for+Android

thanks for the good work so far !

**Comment by dereulenspiegel** [comment]
Thats in the works and the reason I introduced dependency injection so I can easily replace the connection implemenation with a fake one.
Most test will be implemented with Robolectric so they can run in a standard Java VM.

**Comment by dereulenspiegel** [comment]
Except for WizarDroid all dependecies should be available through a maven repo configured in the pom.xml. WizarDroid can be build and deployed to the local repo before building HABSweetie since it is configured as submodule under dependencies/.
For automated nightlies I now only have to create a cloudbees account
